name: Docker frontend Image CI
on:
    push:
        branches: [ "main" ]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Login to Docker Hub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1
        - name: Build and push
          uses: docker/build-push-action@v2
          with:
            context: ./udagram-frontend
            file: ./udagram-frontend/Dockerfile
            push: true
            tags: ${{ secrets.DOCKER_HUB_USERNAME }}/udacity_udagram_frontend:v1.0.1
            cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/udacity_udagram_frontend:buildcache
            cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/udacity_udagram_frontend:buildcache,mode=max
